[package]
name = "aad"
version = "0.2.3"
authors = ["Hikaru Nakashima <nakashima.alg57@gmail.com>"]
description = "Automatic adjoint differentiation library"
edition = "2021"
repository = "https://github.com/nakashima-hikaru/aad"
license-file = "LICENSE"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
RustQuant_autodiff = "0.4.0"

[[bench]]
name = "benchmark"
harness = false