name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev libfreetype6-dev

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Criterion
        run: cargo install cargo-criterion

      - name: Run benchmarks
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cargo criterion --features benchmarks -- --noplot --test
          else
            cargo criterion --features benchmarks
          fi

      - name: Deploy Benchmark Results to GitHub Pages
        if: matrix.os != 'windows-latest'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/criterion
          branch: gh-pages-${{ matrix.os }}
